package com.example.playcheck.dataBaseLinkFiles;

import com.example.playcheck.puremodel.Player;
import com.example.playcheck.puremodel.Referee;
import com.example.playcheck.puremodel.User;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.List;

public abstract class UserLinkToDatabase {

   /*Write a message to the database
    val database = Firebase.database
    val myRef = database.getReference("message")

        myRef.setValue("Hello, World!")

    */


 /*Read from the database
myRef.addValueEventListener(object: ValueEventListener {

        override fun onDataChange(snapshot: DataSnapshot) {
            // This method is called once with the initial value and again
            // whenever data at this location is updated.
            val value = snapshot.getValue<String>()
            Log.d(TAG, "Value is: " + value)
        }

        override fun onCancelled(error: DatabaseError) {
            Log.w(TAG, "Failed to read value.", error.toException())

            */

    FirebaseAuth uAuth;

    DatabaseReference userRef = FirebaseDatabase.getInstance().getReference();
    DatabaseReference rootRef = userRef.child("Referee");
    DatabaseReference rootPlayerRef = userRef.child("Player");

    DatabaseReference rootOrganizerRef = userRef.child("Organizer");
//-----------------------------------------------------------------------------------------------

    //The entity that updates/deletion are going to base on in the database
    User theUser;
    UserLinkToDatabase(User theUser){

        this.theUser = theUser;
        uAuth = FirebaseAuth.getInstance();
    }


    //-------------------------------------------------------------------------------------------
  /*  1. Core CRUD Operations
    These are the fundamental building blocks of any persistence class.

    create(entity) / save(entity) / insert(entity)

    Function: Persists a new record to the database.

    Returns: Often returns the saved entity with its generated ID.

            read(id) / findById(id) / get(id)

    Function: Retrieves a single record by its primary key.

    Returns: An Entity object or an Optional<Entity> (to handle nulls gracefully).

    update(entity) / merge(entity)

    Function: Saves changes made to an existing entity back to the database.

            delete(id) / delete(entity)

    Function: Removes a record from the database.

    existsById(id)

    Function: Checks if a record with a specific ID exists without loading the entire object.

   */



    /*
     Function: Persists a new record to the database.
     */
    public void saveUserToDatabase(){

      /*
      -Since it is a new record:
      -The email and password is used to create the User Authentication in the FirebaseAuth - Database
      -The user ID is automatically generated by Firebase Authentication and saved
       */
        uAuth.createUserWithEmailAndPassword(theUser.getEmail(), theUser.getPassword());

        /*
        The user's ID is needed to add the user to the real time database
         */
        String uid = uAuth.getCurrentUser().getUid();
        theUser.setUid(uid);

        /*
        The users are added to the database based on the account Types using their new generated UID
         */
        if(theUser.getClass() == Referee.class){

            rootRef.child(uid).setValue(theUser);


        } else if (theUser.getClass() == Player.class) {

            rootPlayerRef.child(uid).setValue(theUser);

        } else {

            rootOrganizerRef.child(uid).setValue(theUser);
        }
    }


    /*

    Function: Often returns the saved entity with its generated ID.

     */
    public String getUser(){

        return theUser.getUid();
    }

    /*
    Optional Function
    -This function could be worked on if THERE IS A NEED to change something like Gender for a user
    in the database
    -The changes to other fields in regard to the specific account types will be in their specific
    LinkToDatabase classes

     */
    private void update(){

    }


    /*

    Function: Deletion of a User completely from the database as a whole

     */
   public void delete(String uid){

       userRef.removeValue();


   }


   //----------------------------------------------------------------------------------------------


//    2. Batch Operations
//    To improve performance and reduce database round-trips.
//
//            saveAll(entities)
//
//    Persists multiple records in a single batch.
//
//            deleteAll(entities) / deleteAllById(ids)
//
//    Deletes multiple records efficiently.
//
//    updateAll(entities)
//
//    Updates a collection of entities.


    /*
    To improve performance and reduce database round-trips.
    Persists multiple records in a single batch.
     */
 /*  public void saveAll(List<User> users){

    }



    Deletes multiple records efficiently.
    public void deleteAll(List<User> users){

    }


    Updates a collection of entities.
    public void updateAll(List<User> users){

    }



    3. Query Methods / Finder Methods
    Since you rarely just retrieve by ID, you need methods to find entities based on specific business criteria.

            findBy[Attribute](value)

    e.g., findByEmail(String email) or findByStatus(Status status).

    findBy[Attribute]Containing / findBy[Attribute]Like

    For text searches (e.g., findByNameContaining(String searchTerm)).

    findBy[Attribute]Between

    For date or numeric ranges.

            findAllBy[Criteria](...args)

    Generic methods to return lists based on complex criteria.





    4. Count Operations
    count()

    Returns the total number of records.

    countBy[Attribute](value)

    Returns the count of records matching a specific condition.












    5. Sorting and Pagination
    Essential for API performance and UI display.

            findAll(sort)

    Returns all records sorted by specific fields (ASC/DESC).

    findAll(pageable)

    Returns a slice/page of data rather than the whole table. This usually returns a Page object containing the data and metadata (total pages, current page).














    6. Transaction Management
    While often handled by annotations (@Transactional), the functions themselves define the transactional boundaries.

    executeWithinTransaction(callback)

    A function that ensures a block of code runs within a database transaction (Commit/Rollback).








    7. Relationship/Lazy Loading Handling
    findByIdWithAssociations(id)

    Explicit methods to fetch an entity along with its related data (e.g., findUserWithOrders(id)) to avoid lazy loading exceptions when the session is closed.












    8. Query Execution (Custom/SQL)
    For complex operations that cannot be done via simple method naming.

            executeNativeQuery(sql, params)

    A method to run raw SQL.

    executeStoredProcedure(procedureName, params)

    A method to call database-stored procedures.


  */


}





